# Generated by Django 5.2 on 2025-05-09 02:13

import django.db.models.deletion
from django.db import migrations, models


def load_questions(apps, schema_editor):
    Question = apps.get_model('feedback', 'Question')
    questions = [
        "What is the correct keyword used to declare variables in javascript?",
        "Which of the following variable is used to declare a variable whose value cannot be changed once assigned?",
        """What will be the output of the following code?
            let age = 20;
            if(age >= 20){
                console.log(“age is 20”);
            } else {
                console.log(“age is not 20”);
            }
        """,
        """What will be the output of the following code?
            let age = 50;
            if(age >= 20 && age <= 30){
                console.log(“age is b/w 20 and 30”);
            } else {
                console.log(“age is not b/w 20 and 30”);
            }
        """,
        "What is correct syntax for declaring an array?",
        "In javascript array’s first element will always be at position?",
        "Which method is used to add elements to end of an array?",
        "Which array method is used to loop over an array?",
        "Which property is used for finding total number of elements in an array?",
        "Which of the following method is used to select an element from the DOM?",
        "What is the correct method used to add class to an HTML element using javascript?",
        "Which property is used to change text of HTML element using javascript?"
    ]

    for q in questions:
        Question.objects.create(question_text=q)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch_name', models.CharField(max_length=20)),
                ('batch_time', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=15)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='feedback.student')),
            ],
        ),
        migrations.RunPython(load_questions),
    ]
