# Generated by Django 5.2 on 2025-05-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentFeedback',
            new_name='StudentAnswers',
        ),
    ]
