# Generated by Django 5.2 on 2025-05-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_rename_studentfeedback_studentanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAnswers',
            new_name='StudentAnswer',
        ),
    ]
